AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  episodelist

  Sample SAM Template for episodelist

Resources:
  AddEpisode:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/episodelist-1.0-SNAPSHOT-shaded.jar
      Handler: episodelist.AddEpisode::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED

  EpisodeTable:
    Type: AWS::Serverless::SimpleTable # More info about SimpleTable Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-simpletable.html
    Properties:
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

