AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:

  AddEpisode:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: episodelist.AddEpisode::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          PARAM1: VALUE
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2

  BuildList:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: episodelist.BuildList::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          PARAM1: VALUE

  EpisodeTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

